name: Tests

on:
  push:

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - uses: actions/checkout@v2

      - name: Checkout and install Flutter
        run: git clone https://github.com/flutter/flutter.git

      - name: Add the Flutter path
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Set Flutter root
        run: echo "FLUTTER_ROOT=$GITHUB_WORKSPACE/flutter" >> $GITHUB_ENV

      - name: Setup flutter
        run: |
          flutter channel stable
          flutter doctor

      - name: Build WASM
        run: |
          cd wasm
          ./build_wasm.sh release

      - name: Build Shared Lib
        run: |
          cd shared_lib
          ./build_shared.sh

      - name: Run tests
        run: flutter test
